version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLASK_ENV=production
      - JWT_SECRET_KEY=61df3d4880dabb76e3fa7db84351935e1dad6000edad1df20c3a064f3cda8e7d
      - SECRET_KEY=61df3d4880dabb76e3fa7db84359012309jd09jd210783090c3a064f3cda8e7d
      - DATABASE_URL=sqlite:///intranet.db
    volumes:
      - sqlite_data:/app/instance
    networks:
      - coolify
      - backend-net
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

networks:
  coolify:
    external: true
  backend-net:
    driver: bridge

volumes:
  sqlite_data:
